Repository scribeWiz-team/ScribeWiz, pull requests merged in 2023-04, with the labels that each got.

#54 update: update dependencies versions
  app/build.gradle
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  build.gradle
Labels: Done in 1h

#50 45 modularise request for permissions
  .idea/.name
  .idea/androidTestResultsUserPreferences.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesStorageManagerTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/PermissionsManagerTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NotesDisplayedActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/NotesListFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/RecFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/NotesStorageManager.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/PermissionsManager.kt
Labels: Estimated 7h, Done in 10h

#60 A simple musicxml editor helper function
  .idea/androidTestResultsUserPreferences.xml
  .idea/compiler.xml
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/EditorTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Util/Editor.kt
Labels: Estimated 8h, Done in 10h

#58 Successfully converted the MediaRecorder to an Audio Recorder
  .idea/misc.xml
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/RecFragment.kt
Labels: Done in 3h

#57 Add tests to notesDisplayedActivity
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NotesDisplayedActivity.kt
Labels: Estimated 5h, Done in 4h

#61 Added scrollable friends list, firestore, and fixed login issue
  app/build.gradle
  app/debug.keystore
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/AuthActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/FirebaseUIActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/ProfilePageFragment.kt
Labels: enhancement, Done in 16h

#76 add transcriber to integrate all the processing elements together
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/MusicxmlBuilder.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/NotesGuesser.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/PitchDetector.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/Transcriber.kt
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/MusicxmlBuilderTest.kt
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/PitchDetectorTest.kt
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/TranscriberTest.kt
Labels: help wanted

#78 Added some tests to increase overall coverage and maintanability.
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/EditorTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HelpFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HomeFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/LibraryFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NavigationActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/SettingsFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/HelpFragment.kt
Labels: Estimated 2h, Done in 4h

#77 72 metronome recording
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/RecFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/NotesListFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/RecFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/ShareFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/ViewScoreViewModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/MusicxmlBuilder.kt
  app/src/main/res/layout/fragment_rec.xml
  app/src/main/res/raw/tick.mp3
Labels: Estimated 5h, Done in 6h
