Repository scribeWiz-team/ScribeWiz, pull requests merged in 2023-05, with the labels that each got.

#80 remove idea and update gitignore to avoid future merge conflicts
  .gitignore
  .idea/.gitignore
  .idea/androidTestResultsUserPreferences.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/render.experimental.xml
  .idea/vcs.xml
Labels: Quick Review, Fix

#87 Simple editor in the works
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/EditorTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NotesDisplayedActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Util/Editor.kt
Labels: Done in 10h

#86 Friend requests
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/EditorTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/FirebaseUIActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/Model.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/MusicNoteModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
Labels: Done in 14h

#85 feat: create models for User and MusicNote
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/FirebaseUIActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/NotesListFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/Model.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/MusicNoteModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
Labels: Done in 10h

#103 add models for Challenges and Submissions tables
  app/build.gradle
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengeModelTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengeSubmissionModelTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/MusicNoteModelTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/UserModelTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeSubmissionModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/Model.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/MusicNoteModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
Labels: Done in 10h, Destabilization Sprint

#107 Add badge model and database interaction
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/AuthActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/BadgeDisplayTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesStorageManagerTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/RecFragmentTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/BadgeDisplayActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/FirebaseUIActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/MainActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/NotesStorageManager.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
Labels: Done in 16h

#114 Editor finished
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/EditorTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NotesDisplayedActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Util/Editor.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
  app/src/main/res/layout/notes_displayed_activity.xml
Labels: Estimated 4h, Done in 10h

#108 101 implement voting system at the database side
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengeModelTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengeSubmissionModelTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeSubmissionModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/MusicNoteModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
Labels: Destabilization Sprint

#115 Display challenge notes
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HomeFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NavigationActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesDisplayedActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/ChallengeNotesActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/HomeFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/RecFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeSubmissionModel.kt
Labels: Estimated 4h, Done in 4h

#132 clean code and remove useless fragments
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/AuthActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/BadgeDisplayTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengeModelTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengesFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/EditorTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HelpFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HomeFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/LibraryFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/MainActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NavigationActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesStorageManagerTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ParticipateInChallengeTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/PermissionsManagerTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/RecFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/RecParameterFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/SettingsFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ShareFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/UserModelTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/HelpFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/Fragments/HomeFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/NotesStorageManager.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/PermissionsManager.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/ViewScoreViewModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/BadgeDisplayActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/ChallengeNotesActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/FirebaseUIActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/MainActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/NotesDisplayedActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/ParticipateInChallengeActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ChallengesFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/HelpFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/LibraryFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/NotesListFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/RecFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/RecParameterFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ShareFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeSubmissionModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/Model.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/MusicxmlBuilder.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/NotesGuesser.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/PitchDetector.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/transcription/Transcriber.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/util/Editor.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/util/RecordingParameters.kt
  app/src/main/res/layout/activity_navigation.xml
  app/src/main/res/layout/fragment_challenges.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/MusicxmlBuilderTest.kt
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/NoteGuesserTest.kt
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/PitchDetectorTest.kt
  app/src/test/java/com/github/scribeWizTeam/scribewiz/transcription/TranscriberTest.kt
Labels: Estimated 4h

#135 Added JavaDoc style documentation to public functions.
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/BadgeDisplayTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/PermissionsManager.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/ViewScoreViewModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/NotesDisplayedActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/NotesListFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/RecFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/ChallengeSubmissionModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/Model.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/MusicNoteModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/util/Editor.kt
Labels: documentation

#137 Cleaned up profile page fragment, added testing, linked friends list with database properly
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/AuthActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/models/UserModel.kt
Labels: Done in 6h

#136 rework of home page
  app/build.gradle
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/AuthActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/LibraryFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/MainActivityTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/FirebaseUIActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/MainActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/LibraryFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/NotesListFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ProfilePageFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/RecFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/RecParameterFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ShareFragment.kt
  app/src/main/res/drawable/challenge.png
  app/src/main/res/drawable/help.png
  app/src/main/res/drawable/no_user.png
  app/src/main/res/drawable/scribewiz_logo.png
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/values/strings.xml
Labels: Estimated 8h, Done in 6h

#145 144 move home page into the nav activity
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/BadgeDisplayTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HelpFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HomeFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/PermissionsManagerTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ProfilePageFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/RecFragmentTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/NavigationActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/HomeFragment.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/NotesListFragment.kt
Labels: Estimated 2h

#152 Challenge database tests
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ChallengesFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/ExportTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/HomeFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesListFragmentTest.kt
  app/src/androidTest/java/com/github/scribeWizTeam/scribewiz/NotesStorageManagerTest.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/activities/ParticipateInChallengeActivity.kt
  app/src/main/java/com/github/scribeWizTeam/scribewiz/fragments/ChallengesFragment.kt
Labels: Done in 2h
